### ISSUE TITLE
make paper auto size

### ISSUE THREAD

**Issue by avianmanagement** [clientIO/JointJS_plus#10]
In the kitchen sink example if I add a rectangle to the page and zoom out it zoom out 3 times then when I drag the rectangle to the right it goes off what I assume is the paper.

Is there a way to make the 'paper' expand to fill the scroll area when one zooms out?

That way I can have a large erd diagram on a page and move around it and zoom in and out properly

**Comment by DavidDurman** [comment]
Just a quick update, this is indeed a good suggestion and we're working on that right now... Will be part of the next update (v0.1.2).

**Comment by avianmanagement** [comment]
Thank you very much.
Do you notify users when you update, or do we need to just keep an eye out for announcements ?

**Comment by DavidDurman** [comment]
We will be sending the updates through email once we feel it's ready.
