### ISSUE TITLE
IE9 visualization issue

### ISSUE THREAD

**Issue by albertoferrazzoli** [clientIO/JointJS_plus#11]
![chrome](https://f.cloud.github.com/assets/5681596/1324861/a19e0560-34b9-11e3-814f-fd02bc880842.png)
![ie9](https://f.cloud.github.com/assets/5681596/1324862/a1a13f50-34b9-11e3-8557-7f5b692a11e3.png)

We have some visualization issue with IE9. Please see attached the pictures that show how IE9 does not properly visualize links between nodes. Also the visualization  halo commands is affected.

**Comment by kumilingus** [comment]
fixed in https://github.com/DavidDurman/joint/commit/f48d36a97198f1d5d67df0da1627c2eebf2b212e
