### ISSUE TITLE
Creation of custom link type

### ISSUE THREAD

**Issue by albertoferrazzoli** [clientIO/JointJS_plus#12]
I am developing an app with JointJS+ and I wonder whether it is possible to use the halo to create a custom type link depending on the type of node selected. At the moment it seem possible to create only standard links but could be convenient to have an event that is triggered when the user start dragging the halo link icon just to let the application to create the custom link object.

**Comment by kumilingus** [comment]
Hi Alberto,

there is actually a mechanism how to achieve this.

``` javascript
graph.on('add', function(link) {
  if (link instanceof joint.dia.Link) {
    var type = graph.getCell(link.get('source').id).get('type');
    switch (type) {
    case 'model.Devs':
      link.attr('.connection/stroke-width', '3px'); }})
      break;
    case 'model.Circle':
      link.attr('.connection/stroke', 'red'); }})
      break;
    }
  }
});
```

Would this approach be sufficient for your needs?

Regards

Roman

**Comment by albertoferrazzoli** [comment]
Hi Roman,

Thank you very much. I will try to follow your advice.
Anyway changing link properties only is a bit restrictive. I would prefer to have a different instance to manage instead.
Best regards,
Alberto
