### ISSUE TITLE
JointJS+ and jQueryUI dont work together

### ISSUE THREAD

**Issue by jnekrassov82** [clientIO/JointJS_plus#13]
Hello. 
I need to insert multiple Stencil elements inside the jQuery Accordion. 
When I insert links to jQuery and jQueryUI into the HTML file above the script link to JOINT.JS, then jQueryUI Accordion widget does not work.  When I insert script links to JointJS above the script links to jQuery and jQueryUI, then JointJS seems does not work properly.

From my understanding, the library that is included last, overrules the one that has been included before.
I wonder how I can include JointJS Stencils inside the Accordion.

Jacob

**Comment by DavidDurman** [comment]
Works fine for me if you include jQuery UI after joint.js. Try this in the plugins/ui/Stencil/demo:

index.html:

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8"/>

        <title>Stencil</title>

        <link rel="stylesheet" type="text/css" href="../../../../dist/joint.css" />
        <link rel="stylesheet" type="text/css" href="../stencil.css" />
        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

        <style>
            #paper {
                border: 1px solid gray;
                float: left;
                position: relative;
                width: 500px;
                height: 300px;
                overflow: hidden;
            }
        </style>
    </head>
    <body>

        <p>Drag an object from the stencil on the left to the paper.</p>

        <div id="stencil"></div>
        <div id="paper"></div>

        <script src="../../../../dist/joint.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <script src="../lib/handlebars.js"></script>
        <script src="../dist/template.js"></script>
        <script src="../joint.ui.Stencil.js"></script>

        <script src="./index.js"></script>
    </body>
</html>
```

add the following to the end of index.js:

``` javascript
$('#stencil').prepend('<h3>First</h3><div>First</div><h3>Second</h3>');
$('#stencil').accordion();
```

It's a dirty demo with no styling but the accordion works as expected.

**Comment by jnekrassov82** [comment]
That worked perfectly with the new version of JointJS. Thanks !
