### ISSUE TITLE
joint.shapes.basic

### ISSUE THREAD

**Issue by joelreymont** [clientIO/JointJS_plus#14]
rappid/dist/joint.shapes.uml.js refers to ./joint.shapes.basic (L19) but I can't find the file.

Is this a bug?

**Comment by DavidDurman** [comment]
joint.shapes.basic is part of the joint.js core file. When using the require() - e.g. in NodeJS, both files (joint.shapes.uml.js and joint.shapes.basic.js) must be in the same directory.
