### ISSUE TITLE
Connections that jump and auto-layout

### ISSUE THREAD

**Issue by joelreymont** [clientIO/JointJS_plus#15]
Consider this diagram drawn in the Rappid sample app:

https://www.evernote.com/shard/s2/sh/3f061232-71a7-4c60-af2c-8294d396638c/6ea21cea397264fa6c429ee7a5bb8046

How do I make the connection from state to ISA "jump" over the connections that it's crossing? I'm talking about forming a semicircular bridge at the crossing point.

Also, how do I prevent auto-layout from drawing the line into the shape, e.g. from the circle with 3 dots to port in2 of the purple model rectangle?

**Comment by joelreymont** [comment]
You can see the kind of connection crossing I'm talking about here:

http://gojs.net/latest/intro/links.html

Please scroll to the bottom to Link.JumpOver and Link.JumpGap.

**Comment by kumilingus** [comment]
You can use `joint.routers.manhattan.js` and `joint.connectors.jumpover.js` to do this now.
