### ISSUE TITLE
Draggable / Droppable in JointJS

### ISSUE THREAD

**Issue by jnekrassov82** [clientIO/JointJS_plus#17]
Hello, Dave.

I need to place one object on a Graph inside another and from that moment, the Child object will "belong" to the Parent, so when moved, they will move together. Also, when JSON string is generated to represent the graph, that relationship would be represented somehow as well. Is it possible ? I managed to do the same with

Draggable / Droppable properties in jQuery, but that was not using SVG elements. I am wondering if I can apply these same jQuery properties to the objects we create in the graph.

For example, I will have 3 Classes of objects, A, B, C. Object, belonging to class B can only be placed inside C-class objects. Objects of class A can only go in B. Something of that sort. Please, tell me if this is possible to accomplish.

Thank you !
Jacob

**Comment by DavidDurman** [comment]
Hi Jacob,

This is something we call 'embedding'. See http://jointjs.com/api#joint.dia.Element:embed and http://jointjs.com/api#joint.dia.Element:unembed. Both methods alter the 'embeds' and 'parent' property of cells the former holding the ID's of children while the latter holds the parent cell id.

``` javascript
cellA.embed(cellB);   // cellA.get('embeds') === [cellB.id], cellB.get('parent') === cellA.id
```

**Comment by DavidDurman** [comment]
The check for the 'drop', you could do something like:

``` javascript
paper.on('cell:pointerup'), function(cellView, evt) {
   var shouldEmbedTo = undefined;
   _.each(graph.getElements(), function(el) {
       if (el.getBBox().containsPoint(cellView.model.getBBox().center()))
           shouldEmbedTo = el;
   }
   if (shouldEmbedTo) { shouldEmbedTo.embed(cellView.model); }
}
```

**Comment by jnekrassov82** [comment]
Hello, Roman.

Thank you ! I will try this.
Jacob

**Comment by jnekrassov82** [comment]
Hello again, Roman.

For some reason, cell:pointerup or cell:pointerdown events are not executing. I have another event 
paper.on('blank:pointerdown', function
and it executes, but
paper.on('cell:pointerup'), function
does not execute at all.

Jacob

**Comment by DavidDurman** [comment]
We've created a tutorial on Reparenting here: http://jointjs.com/tutorial/hierarchy#reparenting. I believe this thread can be closed. Let me know if that's not the case and I'll reopen it.

**Comment by sugir93** [comment]
how to implement minview in jointujs?
