### ISSUE TITLE
Regression in Label formatting in 0.8 release

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#22]
There is a regression on the label formatting for the 0.8 release.  You can see it in the demo here : http://jointjs.com/demos/links

The colored labels and positioning are missing.

Behavior witnessed with : 

Chrome : 32.0.1700.77
FireFox : 26.0
Safari : 7.0.1 (9537.73.11)

**Comment by kumilingus** [comment]
Thanks for noticing! Fixed in https://github.com/DavidDurman/joint/commit/3a093050f98a90735e8bc7d755f8e6c10db6b039.

**Comment by DavidDurman** [comment]
Closing as this is fixed.
