### ISSUE TITLE
How to use attr to delete an attribute

### ISSUE THREAD

**Issue by ryang123** [clientIO/JointJS_plus#23]
Sometimes, attributes are set that a user may later want to remove, such as marker source/target arrows or dasharray.  It's possible to add a placeholder value, such as dasharray of 1,0, and that is my temporary workaround, but I'd like to actually remove them for efficiency in storing the JSON. I might be missing it, but I don't see a function that supports this.

I see that there is a new parameter (opt) for the attr function, but am not sure if this (or another existing function) offers a path to what I want.

If there is not already a function that supports this, one way to get there would be to allow users to delete an attribute in the form element.attr('.marker-target/d', ''), and then check for an empty string versus null in the attr function, and unset the value there if it is an empty string.  I will likely implement it that way unless you indicate there is already a function that does what I want to do.

**Comment by DavidDurman** [comment]
Fixed and will be released in the next version of JointJS (v0.9). We've added a new method: `removeAttr()` that does just that. Also, a related utility method will be available: `joint.util.unsetByPath()`.
