### ISSUE TITLE
TypeError : ctm is undefined  -  PaperScroller  -  FireFox

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#24]
Received this error with a PaperScroller implemented.

TypeError : ctm is undefined

FireFox : version 26

Code snippet  (joint.ui.PaperScroller.js)  Line 95 : 

```
var ctm = this.options.paper.viewport.getCTM()
      , sx = ctm.a
      , sy = ctm.d
      , cx = this.el.clientWidth / sx / 2
      , cy = this.el.clientHeight / sy / 2;
```

**Comment by DavidDurman** [comment]
Can't reproduce this unfortunately, same Firefox version (on OS X). Do you have a specific scenario where this happens?

**Comment by kmansel** [comment]
Hey David,

It seems as though I'm getting this when i'm hiding the div with the paperscroller attached.  So i'm trying to build the graph, output the svg, and then hide the graph at runtime of the page.  So instead of showing the graph itself, i would show the svg representation in place of the graph.  This might be causing the problem.  I'll find out more and let you know.  If there is a better way to do that, I am totally all ears.  :)

**Comment by kmansel** [comment]
This was a problem on our side.  Essentially calling a .center() command before the paper was set.  :P
