### ISSUE TITLE
Manhattan link routing avoiding elements

### ISSUE THREAD

**Issue by DavidDurman** [clientIO/JointJS_plus#26]
As requested by Santiago, it would be great to have link routing so that links avoid other elements.

TIP: use A\* algorithm (or some of its variations) to find the shortest path between two elements while avoiding obstacles.

**Comment by trikanna** [comment]
awesome!

**Comment by DavidDurman** [comment]
Implemented in JointJS v0.9. http://jointjs.com/blog/jointjs-0-9-released.html.

**Comment by dorondru** [comment]
I have a problem with manhattan routing where after resizing objects,  links are no longer connected to the boundary of a shape but suddenly connect to its center. Also when that happens, arrowheads point in the  wrong direction.
