### ISSUE TITLE
Update to drop shadow filter

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#28]
This update to the dropshadow filter will allow the user to send in an opacity for the drop shadow.  Uses the feComponentTransfer -> feFuncA with a slope to set the opacity of the drop shadow color.

Example of setting....

```
filter: {
    name: 'dropShadow',
    args: {
        dx: 4,
        dy: 4,
        blur: 0,
        color: 'black',
        opacity: 0.1
    }
}
```

Code to update : 

```
dropShadow: function(args) {

    return _.template('<filter><feGaussianBlur in="SourceAlpha" stdDeviation="${blur}"/><feOffset dx="${dx}" dy="${dy}" result="offsetblur"/><feFlood flood-color="${color}"/><feComposite in2="offsetblur" operator="in"/><feComponentTransfer><feFuncA type="linear" slope="${opacity}"/></feComponentTransfer><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>', {
        dx: args.dx || 0,
        dy: args.dy || 0,
        color: args.color || 'black',
        blur: _.isFinite(args.blur) ? args.blur : 4,
        opacity: _.isFinite(args.opacity) ? args.opacity : 1
    });
},
```

**Comment by DavidDurman** [comment]
Great stuff, thanks! Just put it in. Will be part of the coming release.

**Comment by kmansel** [comment]
?Cool!

Any updates on the drop shadow connection boxes?  We really want to put drop shadows on our diagram cells, but also have the halo dragging new links work.  At least it'll make the stakeholders all giddy when they see our next release.  :)

-kev
