### ISSUE TITLE
Tooltips positioned incorrectly for SVG path elements in Firefox

### ISSUE THREAD

**Issue by DavidDurman** [clientIO/JointJS_plus#30]
When tooltips are used on shapes that are built from SVG path elements, their position is a bit off in Firefox. This seems to be due to wrong values returned from getBoundingClientRect() DOM method on SVG path elements in Firefox.

**Comment by kumilingus** [comment]
Can not be reproduced.

**Comment by JoseGoncalves** [comment]
I reported this problem to David.

This problem can be reproduced with the test case that I've setup at: http://plnkr.co/edit/V43Rrh

**Comment by kumilingus** [comment]
Hi Jose, thank you for the test case. It's fixed and will be included in today's release.

**Comment by JoseGoncalves** [comment]
Good to know. Thanks.
