### ISSUE TITLE
Property sheet Tab button removing visual elements

### ISSUE THREAD

**Issue by luicaps** [clientIO/JointJS_plus#32]
Hi,

Not sure how to call this bug or to explain, but here it goes. When you're on the last UI component of some tab and hit "tab" button, it changes the focus for the first component of the next tab, but not opening it, causing the tab title to be removed.

To easily reproduce it, just focus on any text box or visual element on the property sheet and keep hitting the tab button, making sure some of the tabs of the sheet are closed.

I did it on Chrome version 35.0.1916.153 m

This bug can be reproduced in the Rappid default example on jointjs.com. See the image:

![rappidbug](https://cloud.githubusercontent.com/assets/5818668/3564931/03ac11be-0a9f-11e4-9e54-7fee8139a950.png)

**Comment by kumilingus** [comment]
Hi, that's fixed.

```
 .inspector .group.closed .field { display: none; }
```

It will be part of the next release.
