### ISSUE TITLE
Issue with text fields on Inspector

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#33]
I've noticed recently a behaviour on the Inspector plugin that I think should be improved.

Say that you have created an Inspector and set the 'live' property to 'true'. When some value is set in a text input field for a given property of a shape or link, It's required to press enter or to click on the inspector area for the value to be set. If, for instance, a text value is set on a shape and the user after that immediately click in another shape to set other property, the value that was previously set is lost.

**Comment by DavidDurman** [comment]
On our todo list already. This should be fixed in the next release.

Thanks!

**Comment by DavidDurman** [comment]
Can be fixed by calling `inspector.updateCell()` just before the `inspector.remove()` in applications. An example of this is in the new Rappid demo that will be released in the coming days.

**Comment by JoseGoncalves** [comment]
I've verified that the solution that you've indicated works.
Thanks David!

**Comment by JoseGoncalves** [comment]
Hi David,

I've detected a problem with this solution. I have a situation were I change the color fill attribute of a polygon shape in reaction to changes in a text input inserted in a custom data field for that shape. After this, when I select another shape with the mouse, the call to `inspector.updateCell()` removes my color assignement to the previous selected shape.
Pleas tell me if this information is not enough for you to reproduce the problem, because, if so, I can setup an test app to demonstrate it.

**Comment by DavidDurman** [comment]
Hi Jose,

A simple test app would be very helpful. If you could set this up, that'd be great.

**Comment by JoseGoncalves** [comment]
I've setup a test app based on your Inspector demo. It is at:

http://plnkr.co/edit/9g6hWZOrHJXXEHmVH4pi

To replicate the problem, select a shape, add any name in the inspector, after which the shape will be filled with blue color, then select the other shape and the color of the previous one will revert to the default.

When setting this up I found that the problem is related with using a render event callback for the inspector. Without this callback set all is OK.

**Comment by kumilingus** [comment]
Hi Jose,

apparently `inspector.off('render')` causing the issue. The Inspector binds its own callback on `render` event for internal purposes. If you wish a callback to be fired only once please use method `once()` (http://backbonejs.org/#Events-once) or make a change to your code like this:

```
    inspector.on('render', function onRender() {
        // Do custom action on inspector render
        inspector.off('render', onRender); // remove only this callback
    });
```

**Comment by JoseGoncalves** [comment]
Thank you for the info! Did not know about the once() method, which was exactly what I was looking for.

BTW, I think it's better that you update your [inspector example in the web site](http://www.jointjs.com/rappid/docs/ui/inspector#create) to include the call to `inspector.updateCell()` when cleaning up the old inspector.
