### ISSUE TITLE
joint.shapes.uml.State do not change properties from inspector

### ISSUE THREAD

**Issue by luicaps** [clientIO/JointJS_plus#34]
Hello,

I created an element based on uml state from JointJS, taking the basic Rappid application as basis.

Recently I added the option to save and load the model based on JSON.stringify(graph). It works great, but the content of this element always reappeared with the default content when reloaded, instead of the the one I changed through the inspector.

I did this in the basic Rappid application on the uml state element and got the same behavior. When you change the content of the state (name and events), this information is changed in the paper (changing the .uml-state-name and .uml-state-events content), but the base var do not change (name and events in the case), causing the JSON generated from the graph to have only the first content provided (probably from the stencil, which is the case).

Somehow when some property is changed in the inspector, the "change:name" and "change:events", are not being called.

I don't understand quite well the way the elements are created and described in the inspector yet, so I couldn't make it happen, but I see that the class uml element works correctly compared to state.

**Comment by kumilingus** [comment]
Fixed in v0.9.1 (it can be downloaded from https://github.com/DavidDurman/joint/tree/master/dist)
