### ISSUE TITLE
PaperScroller error on v0.9.1 jointjs integration

### ISSUE THREAD

**Issue by luicaps** [clientIO/JointJS_plus#35]
Hi,

I took the Rappid demo to integrate with JointJS 0.9.1 before doing it to my code. I changed all joint sources to the newest commited versions from the repository and I get this error:

Uncaught TypeError: Cannot set property 'paper' of undefined main.js:65
Backbone.Router.extend.initializePaper main.js:65
Backbone.Router.extend.initializeEditor main.js:21
Backbone.Router.extend.home main.js:14
_.extend.execute joint.js:16463
(anonymous function) joint.js:16452
(anonymous function) joint.js:16679
some joint.js:12536
_.extend.loadUrl joint.js:16677
_.extend.start joint.js:16643
(anonymous function) index.html:111

I don't know if it helps or is related to the problem, but I added this line,

console.log(JSON.stringify(this.paperScroller));

in the line 45 of main.js (Right after the creation of PaperScroller instance), and it gives this print:

'Attr.ownerElement' is deprecated and has been removed from DOM4 (http://w3.org/tr/dom).

**Comment by luicaps** [comment]
Oh,

The second issue I mentioned is because I'm using JSON.stringify. It seems the paperScroller is all right. Probably something with options then.

**Comment by DavidDurman** [comment]
It doesn't make sense to serialize views (as paper scroller is). You can only serialize models: graph, element, link
