### ISSUE TITLE
Inspector: Focus on list with several inputs

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#42]
With the Inspector plugin, in a situation were we have a list of objects in which an object has more that one input, when we add a new item the focus goes to the last element.
I think a better choice is to give focus to the first input, what can be done by replacing in method `addItemList()`;

``` javascript
$listItem.find('input').focus();
```

with

``` javascript
$listItem.find('input:first').focus();
```

**Comment by kumilingus** [comment]
Thank you Jose, that's brilliant. Fixed in v1.5.
