### ISSUE TITLE
Issue with inspector's updateCell()

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#43]
Playing around with expressions to switch the visibility of inputs I found that the updateCell() method is updating hidden inputs when called. It seems to me that this should be fixed by replacing in the beginning of the iteration function;

``` javascript
if ($attribute.hasClass('hidden')) return;
```

with;

``` javascript
if ($attribute.parent().hasClass('hidden')) return;
```

**Comment by kumilingus** [comment]
You are right. Fixed in v1.5.

``` javascript
if ($attribute.closest('.field').hasClass('hidden')) return;
```

Thanks again!
