### ISSUE TITLE
Code fix for joint stencil module

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#44]
Around line 823...inside the remove function of the joint.ui.stencil.js module.  

When you called remove on the stencil element, it wouldn't call remove on it's paper views.  So we would be leaking event handlers.  This should fix the problem.

```
remove: function() {
        _.invoke(_.values(this.papers), 'remove');
        this.papers = {};

        if (this._paperDrag) {
            this._paperDrag.remove();
            this._paperDrag = null;
        }
```

**Comment by DavidDurman** [comment]
Good catch! Can be simplified to:

``` javascript
_.invoke(this.papers, 'remove');
```

It's in.

**Comment by DavidDurman** [comment]
By simplified I mean only the line `_.invoke(_.values(this.papers), 'remove');`
