### ISSUE TITLE
TextEditor problem when using jQuery UI

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#45]
Hi,

If an app uses the TextEditor plugin with jQuery UI the folllowing error occurs in the render call:

**Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'off'**

This problem can be reproduced in the TextEditor demo app supplied with Rappid by replacing in index.html:

``` html
<script src="../../../../dist/joint.js"></script>
```

with:

``` html
<script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="http://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="../../../../dist/joint.nojquery.js"></script>
```

Best regards,
José Gonçalves

**Comment by JoseGoncalves** [comment]
Removing the `autocomplete: 'off'` attribute in the call that creates the textarea object in the `render` method removes this error.

**Comment by kumilingus** [comment]
The textarea attributes are configurable via options now.

```
new joint.ui.TextEditor({
    textareaAttributes: {
          autocorrect: 'off',
          // autocomplete: 'off',
          autocapitalize: 'off',
          spellcheck: 'false',
          tabindex: '0'
    },
    ...
});
```
