### ISSUE TITLE
Stencil improvement suggestion

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#46]
Working recently with Kendo UI, I found a neat feature in their drag-and-drop implementation that it would be nice to have also when dragging JointJS elements from the stencil.

In KendoUI, when the user tries to drop an object to an area that is not acceptable, an animation is played "returning" the object to the original position. This gives an instant feedback to the user that the action performed was not allowed. You can see this behaviour in this demo:

http://demos.telerik.com/kendo-ui/dragdrop/

**Comment by DavidDurman** [comment]
Yes, that's a nice one. I have good news for you, we have this in place. We're working on a continuous deployment service where you can just log in and get new version of Rappid on a per-feature basis much more quickly than currently. I strongly believe we'll have this ready in weeks time. Then you'll be able to get the latest version with animated stencil drop from there.

**Comment by JoseGoncalves** [comment]
Nice to hear that. That's really good news!
