### ISSUE TITLE
When using Sticky Links, the initial draw of the graph shows the links inside elements.

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#47]
when we have our sticky links up, and we render a graph…it seems as though the lines are generating in the middle of the objects…once I move the element, the line snaps back to the edge. 
![pastedgraphic-9](https://cloud.githubusercontent.com/assets/1252780/6139782/795891f2-b144-11e4-88b7-5fdbfc549eb8.png)

![pastedgraphic-10](https://cloud.githubusercontent.com/assets/1252780/6139785/82c0285e-b144-11e4-9467-989de1d693c1.png)

**Comment by DavidDurman** [comment]
Do you have an example? Is there any specific configuration you use? (async rendering, perpendicular links, ...). Could you also please describe/show how do you load the graph?

**Comment by kmansel** [comment]
There really isn't anything crazy about the setup.  We build the graph by looping over some components, then adding the links to the graph next.  Perpendicular links are set to false.

Here is my paper obj

![image](https://cloud.githubusercontent.com/assets/1252780/6219428/05f6b9d4-b5de-11e4-8226-be8bc9c6f999.png)

**Comment by DavidDurman** [comment]
Hmmmm, right.... let us have a closer look then...

**Comment by DavidDurman** [comment]
We can't get to reproduce this. Could you please send the definition of one of your shapes?

**Comment by kmansel** [comment]
HI David, here is the markup of the shape.  We aren't using primitives, but path's.  Hopefully that's what you were referring to.  If you need more info, let me know and i'll shoot that over too.

Here are a few of them.

diamond : 
`<path class="js-markup js-stroke" d="m0,45l45,-45l45,45l-45,45l-45,-45z"/>`

cloud : 
`<path class="js-markup js-stroke" d="m50.22813,0.50378c-0.1763,0.00556 -0.3465,0.02037 -0.52361,0.03809c-2.83179,0.28205 -5.33119,2.07919 -6.60079,4.75691l-0.673,2.02641c0.1451,-0.70216 0.3682,-1.38339 0.673,-2.02641c-2.2641,-2.34591 -5.4423,-3.42885 -8.5824,-2.92074c-3.1406,0.50793 -5.8679,2.54555 -7.3583,5.49902c-4.2075,-2.59139 -9.4524,-2.43456 -13.51,0.4091c-4.05744,2.84354 -6.22009,7.87844 -5.56281,12.95784l0.43014,2.0645c-0.19449,-0.6764 -0.33949,-1.3643 -0.43014,-2.0645l-0.06553,0.1903c-3.52699,0.3845 -6.41954,3.121 -7.17113,6.7835c-0.75105,3.6625 0.8111,7.4203 3.87089,9.3141l4.77739,1.1607c-1.6682,0.1372 -3.33352,-0.2671 -4.77739,-1.1607c-2.36038,2.6436 -2.90322,6.5575 -1.34628,9.7898c1.55664,3.2321 4.88145,5.0934 8.31146,4.6714l2.0851,-0.5519c-0.671,0.2807 -1.3676,0.4635 -2.0851,0.5519c1.9473,3.5845 5.176,6.1995 8.9662,7.2399c3.7901,1.0406 7.816,0.4257 11.1726,-1.7029c2.7383,4.3183 7.5984,6.5866 12.4722,5.8224c4.8738,-0.7641 8.894,-4.4281 10.3219,-9.3997l0.4953,-2.778c-0.0742,0.9439 -0.2352,1.8716 -0.4953,2.778c3.352,2.1983 7.5688,2.3222 11.03209,0.3235c3.4637,-1.9987 5.62492,-5.81 5.65651,-9.961l0.0284,-1.90594c9.79794,2.78577 11.45332,-1.90076 13.16761,-6.32356c1.71441,-4.423 0.73275,-10.79751 -4.86552,-13.2529c1.14771,-2.8201 1.07951,-6.0278 -0.18709,-8.7909c-1.2667,-2.7628 -3.6033,-4.81657 -6.41371,-5.62269c-0.62899,-3.66196 -3.22129,-6.60753 -6.64769,-7.57295c-3.42601,-0.96549 -7.074,0.22504 -9.3678,3.06348l-1.3932,2.34981c0.3559,-0.84977 0.821,-1.64182 1.3932,-2.34981c-1.6171,-2.23084 -4.1532,-3.48966 -6.7972,-3.40606l0,0l0,0z"/>`

cylinder : 
`<path class="js-markup js-stroke" d="m63,9.77893c0,5.39969 -14.10284,9.77707 -31.49968,9.77707m31.49968,-9.77707l0,0c0,5.39969 -14.10284,9.77707 -31.49968,9.77707c-17.39807,0 -31.50032,-4.37738 -31.50032,-9.77707m0,0l0,0c0,-5.40152 14.10225,-9.77893 31.50032,-9.77893c17.39684,0 31.49968,4.37741 31.49968,9.77893l0,39.10834c0,5.40094 -14.10284,9.77838 -31.49968,9.77838c-17.39807,0 -31.50032,-4.37744 -31.50032,-9.77838l0,-39.10834z"/>`

**Comment by DavidDurman** [comment]
Hi Kevin, thanks for this. Would it be possible to send the complete shape definition? I mean the joint.shapes.yournamespace.YourShape object? That would make the debugging much easier. Thanks.

**Comment by kmansel** [comment]
Hi David,  basically the shape definition we have being built is a combination of classes and sub classes building themselves at runtime.  I can tell you the general markup of the shapes follows most of your documentation.

The path is the .outer class.  In the image below, you'll see the path in the .outer hash definition.

```
markup: '<g class="element-container"><rect class="sizer"/><g class="scalable"><path class="outer"/></g><g class="content"><text class="text"></text><path class="underline"></path></g></g>',

```

![image](https://cloud.githubusercontent.com/assets/1252780/6419488/78888dc8-be72-11e4-844b-840a6b0d3b61.png)

**Comment by kmansel** [comment]
Hi David,

More information for you here.  When the initial draw of the diagram comes into play, I put a watch expression in to where the point should be hitting the stroke.  I also took a snapshot of the parameters when I move it manually and the connection points sync back up to path lines.

I've found this data in the while loop of the findIntersection function in the main joint.js codebase.

It's like the link has a different starting point on graph build, than it does once I move it?

![image](https://cloud.githubusercontent.com/assets/1252780/6493786/e5c53c12-c271-11e4-8599-e1593d01dcf6.png)

![image](https://cloud.githubusercontent.com/assets/1252780/6493844/6a19530e-c272-11e4-84de-3e99f72d7367.png)

**Comment by DavidDurman** [comment]
Hard to see where the issue is. The markup looks alright. If you look at the JointJS/src/core.js file and find the `shapePerimeterConnectionPoint` method (https://github.com/DavidDurman/joint/blob/master/src/core.js#L352), you can see how the outer element  (magnet) is being found. If there is a `.scalable` element, we assume it is its first child. If not, we try the first child of the `.rotatable` SVG element. In your case though, you do have `.scalable` SVG element that has the `<path class="outer"/>` SVG element as its first child so this one should be used for finding the intersection point of the link. I'm quite confused why this does not happen on the initial graph build. Could that be that you're somehow dynamically changing the SVG elements inside your shapes? If we could get to see the application with the ability to quickly debug it, that would help tremendously. Or if we had a working use case with your shapes and a simple graph loaded that demonstrates the issue, that would also help a lot. Do you think you can provide that?

**Comment by kmansel** [comment]
Hi David, yes to your question of providing you with a demo version.  I could create you an account, and allow you in to see the diagram experience, however the sticky links isn't enabled in the live demo...would you be able to debug into that and turn it on to see what's happening?  Remember it's happening when you first see the graph, once I move an element around, the links snap back into place.  I think if I could either create a standalone version that mimics the same functionality, to show you what's happening, that would work, or even better, if you'd like to do a remote debugging session, where i can show you from my environment exactly what is happening, that would be the best.  What do you recommend?  This is one of those features we need to have working with a month.  I'm confident we can get it solved.

**Comment by DavidDurman** [comment]
If you could put it online somewhere for me to see, that'd be great! Remote debugging session is also an option, the only problem with this is for us to sync the times. Shall we take this discussion to email?
