### ISSUE TITLE
CSS Naming Convention

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#49]
We are noticing sometimes the css naming convention is rather basic.  Especially if you're using the tooltip plugin, as those css classes clash with bootstrap.  Is there a push in the near future to name your css classes a bit more specific?

For example :  instead of .tooltip, maybe something like .ui-joint-tooltip

**Comment by DavidDurman** [comment]
We might consider this. In the near future, as part of redesign of Rappid components and support for themes, we're planning to switch to Sass. This will not only make it easy to restyle components but also bring the possibility to namespace the CSS.

**Comment by JoseGoncalves** [comment]
Also noticed this issue using Rappid's Tooltip within an app that uses Bootstrap CSS.

**Comment by oklymenk** [comment]
+1. Had to work around a conflict with .label class (using Bootstrap)

**Comment by kumilingus** [comment]
Fixed in v2.0. Added `joint-` prefix to all Rappid/JointJS views.

**Comment by kmansel** [comment]
👍
