### ISSUE TITLE
Sticky Links not so sticky on browsers other than Chrome

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#50]
See images below for Chrome, FireFox, Safari and IE implementations.  Chrome looks great!  The others are behaving a bit differently...

![pastedgraphic-11](https://cloud.githubusercontent.com/assets/1252780/6139830/4dd0ced6-b145-11e4-96e1-73dd0ab17501.png)

![pastedgraphic-12](https://cloud.githubusercontent.com/assets/1252780/6139831/51b20e84-b145-11e4-91df-bc24dceb60c4.png)

![pastedgraphic-13](https://cloud.githubusercontent.com/assets/1252780/6139833/559daada-b145-11e4-81f0-71824a593f38.png)

![pastedgraphic-14](https://cloud.githubusercontent.com/assets/1252780/6139834/59cee222-b145-11e4-946e-fecdb033e037.png)

**Comment by kumilingus** [comment]
I believe this is not an issue anymore. Please reopen if I am wrong. Thanks.
