### ISSUE TITLE
Path finder algorithm in BPMN

### ISSUE THREAD

**Issue by JoseGoncalves** [clientIO/JointJS_plus#54]
A common use case in a BPMN diagram is to find paths between a set of activities.
I would like to request that you add an algorithm to Rappid that could provide an easy (and efficient) way to calculate this. As an example for what is needed take a look to the following diagram:
![bpmn_path](https://cloud.githubusercontent.com/assets/3037740/6465535/a2bd42ba-c1b9-11e4-886d-526310d0b6c3.png)
The red higllighted path is the output for this algorithm given as input activities A, C and D.

**Comment by DavidDurman** [comment]
This is now partially implemented in the `shortestPath()` method of the `dia.GraphUtils` plugins (http://jointjs.com/rappid/docs/dia/graphUtils). However, this could be extended with another method for finding _all_ the paths, not only the shortest one.
