### ISSUE TITLE
joint.ui.SelectionView bug fix

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#56]
Starting in the remove function  (around line 525 in the clean version)

You are missing an event un-registration function, and since you weren't including the function in the .off() call, two different selection views would unregister each other's event listeners.

Old Code : 

```
remove: function() {

        Backbone.View.prototype.remove.apply(this, arguments);
        $(document.body).off('.selectionView');
    },
```

New Proposed Code : 

```
remove: function() {

        Backbone.View.prototype.remove.apply(this, arguments);
        $(document.body).off('.selectionView', this.adjustSelection);
        $(document).off('.selectionView', this.pointerup);
    },
```

**Comment by kumilingus** [comment]
Fixed. Available in the next release. Thank You.
