### ISSUE TITLE
Error deleting a list item in the Inspector

### ISSUE THREAD

**Issue by oklymenk** [clientIO/JointJS_plus#59]
This worked in 0.9.2 but seems to be broken in 0.9.3/Rappid 1.5.

To reproduce, configure the inspector to have a list of objects, add 2 objects and then delete the first one by clicking the '-' button. The object disappears from the inspector but the model still contains two objects. It looks like the objects get moved up in the array but the last one does not get deleted.

If you start with A, B, C and then delete A, the model will contain B, C, C
If you start with A, B, C and then delete B, the model will contain A, C, C
If you start with A, B, C and then delete C, the model will contain A, B, C

In the example above, if you delete an object (A, B, or C), and then try to add a new one, the fields for the new object will contain the values for C.

``` javascript
cellView.model.prop('people', [
    {
        firstName: 'James',
        lastName: 'Bond'
    },
    {
        firstName: 'Ethan',
        lastName: 'Hunt'
    }
]);

cellView.model.on('change:people', function () {
    return; // inspect the model here
});

var inspector = new joint.ui.Inspector({
    inputs: {
        people: {
            type: 'list',
            item: {
                type: 'object',
                properties: {
                    firstName: {
                        type: 'text',
                        label: 'First Name'
                    },
                    lastName: {
                        type: 'text',
                        label: 'Last Name'
                    }
                }
            }
        }
    },
    cellView: cellView
});
```

**Comment by kumilingus** [comment]
Hi, thanks for reporting this. The inspector issue with objects nested within an array has been resolved and the fix will be part of the next release.

Please contact me at roman@client.io if this issue is blocking you right now.

**Comment by JoseGoncalves** [comment]
I also encountered this issue in my app and had to find a quick workaround for it in Rappid 1.5.1.
The following patch worked for me:

``` patch
Index: joint.ui.inspector.js
===================================================================
--- joint.ui.inspector.js   (revision 1458)
+++ joint.ui.inspector.js   (revision 1471)
@@ -1455,7 +1455,7 @@
         return options;
     },

-    updateCell: function($attr, attrPath) {
+    updateCell: function($attr, attrPath, delItem) {

         var cell = this.getModel();

@@ -1499,6 +1499,11 @@
                     this.setProperty(path, [], { rewrite: true });
                 } else {
                     this._tempListsByPath[path] = [];
+                    if (delItem) {
+                        var i;
+                        for (i=1; byPath[path + '/' + i]; i++);
+                        this.unsetProperty(path + '/' + i);
+                    }
                 }

                 break;
@@ -1672,7 +1677,7 @@
         this.trigger('render');

         if (this.options.live) {
-            this.updateCell();
+            this.updateCell(null, null, true);
         }
     },

```
