### ISSUE TITLE
joint.ui.stencil.js bug fix

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#60]
Hey Guys,

in the joint.ui.stencil.js file, there is the onDragStart and onDrag functions.  If we don't add evt.preventDefault() functions at the top of these events, the browser will sometimes allow the click and drag to change the user selection in the window, highlighting text when we don't want it to.

This also happens pretty much anytime when clicking and dragging through the paper, then the browser will do it's default text selection behavior....such as grabbing a cell and dragging the mouse off the paper with it.

```
onDragStart: function(cellView, evt) {
     evt.preventDefault();  //add here
     ........

onDrag: function(evt) {
     evt.preventDefault();  //add here
     ........
```

**Comment by kumilingus** [comment]
Fixed. Available in the next release.
