### ISSUE TITLE
joint.ui.SelectionView bug

### ISSUE THREAD

**Issue by kmansel** [clientIO/JointJS_plus#61]
Ok,

So this is an interesting repro.  Say you have a paper, and it scrolls down a bit.  You have an object on the paper.  The object is within view.  You click and drag to start your selection.  Keep dragging the selection down, so the paper scrolls down.  Now try to go back up the scrolled paper.  The calculation of the selection box along with the mouse position is now off.

Let me know if you need more explanation on this one.

I can shoot over a video to show it happening if that will help.  Just let me know which email to use.

**Comment by kumilingus** [comment]
Fixed. Available in the next release. Thank you!
