### ISSUE TITLE
Bug : ui.TextEditor double click

### ISSUE THREAD

**Issue by franzsc** [clientIO/JointJS_plus#64]
When the text must be edited several times, it’s gets complicated to double click the editor and sometimes you must double click more than once. 

You can reproduce too this bug on your demo on trying to edit the text several times: http://jointjs.com/rappid/docs/ui/textEditor

**Comment by kumilingus** [comment]
The issue was introduced in the demo example, that was instantiating the TextEditor plugin in wrong way. Not in the TextEditor itself. Fixed in `v1.7`.
