### ISSUE TITLE
Broken SVG links generated by joint.dia.Paper.prototype.toSVG in IE 9/10/11 (Fix suggested)

### ISSUE THREAD

**Issue by KarolBuchta** [clientIO/JointJS_plus#66]
Version Rappid v1.7.0

The toSVG method exports SVG that has broken links (not clickable anymore) when using IE9/10/11.
This seems to be a known behaviour in IE, within the xml serialization. I fixed this on my own after the serialization step. It's also necessary to set the namespace on the svg itself correctly. See my solution below for a basic guide.

// 4. Fix for IE set namespace for links, otherwise they don't work.
  V(svgClone).attr({"xmlns:xlink":"http://www.w3.org/1999/xlink"});

  function serialize() {
    // Now, when our `svgClone` is ready, serialize it to a string and return it.
    var xml = (new XMLSerializer()).serializeToString(svgClone);

```
var $html = $('html');
if($html.hasClass('ie9') || $html.hasClass('ie10') || $html.hasClass('ie11')) {
  //This string ends up in ie9: xmlns:NS1="http://www.w3.org/2000/svg" NS1:xlink="http://www.w3.org/1999/xlink"
  var start = xml.indexOf('<svg');
  var end = xml.lastIndexOf("/svg>");
  xml = xml.substring(start, end + 5);
  //The following two are attributes on the svg tag
  xml = xml.replace(/xmlns:NS[\d+]=\"http:\/\/www.w3.org\/2000\/svg\"/g, '');
  xml = xml.replace(/NS[\d]+:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"/g, 'xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"');
  //The following fixes markup destruction within the svg
  xml = xml.replace(/NS[\d]+:href=/g, 'xlink:href=');
  xml = xml.replace(/xmlns:NS[\d]+=\"http:\/\/www.w3.org\/1999\/xlink\"/g, '');
}

return xml;
```

  }

**Comment by DavidDurman** [comment]
Hi Karol,

I just filed a bug in our internal issue tracking system. This is indeed a bug and should be fixed.

Thanks,
David

**Comment by kumilingus** [comment]
Hi,

the issue should be fixed by https://github.com/clientIO/joint/pull/308.

Best,
Roman
