### ISSUE TITLE
With the parameter "async": true the fork action doesn't work well

### ISSUE THREAD

**Issue by fbrillante** [clientIO/JointJS_plus#69]
If the parameter async: true is set into the Paper, the fork action from the halo does not work and this error can be found in browser's console:

> TypeError: this._cloneView is undefined
> this._cloneView.pointerdown(evt, x, y);

The issue can be easily reproduced also in Rappid examples, such as "BPMN Editor".

**Comment by kumilingus** [comment]
Hi,

thanks for reporting this. We are preparing a fix for that. It's important to pass `async: false` option when cloning an element.

`options.graph.addCells([clone, link], { halo: this.cid, async: false });`

**Comment by kumilingus** [comment]
Fixed in v2.0.
