### ISSUE TITLE
Feature Request: Bypass grid size in combination with keypress

### ISSUE THREAD

**Issue by ryang123** [clientIO/JointJS_plus#7]
The grid feature is very useful and can be adjusted dynamically using paper.options.gridSize, but sometimes it is useful to override the grid just for a specific action on an element.  It would be nice if there were a keyboard key that, when pressed in combination with a mouse event on an element, bypassed the grid (to size 1) for fine tuning without leaving the grid changed for subsequent actions.

**Comment by DavidDurman** [comment]
This seems to be quite application specific. One can always set, as you correctly pointed out, the paper.options.gridSize at any time and reset to the original one after the action is performed.

With KeyboardJS (http://robertwhurst.github.io/KeyboardJS/), this could be done with something like:

``` javascript
var originalPaperGridSize = paper.options.gridSize;
KeyboardJS.on('shift', 
    function onDown() { paper.options.gridSize = 1; },
    function onUp() { paper.options.gridSize = originalPaperGridSize; }
);
```

**Comment by ryang123** [comment]
That will work for me.  Thanks!
