### ISSUE TITLE
Cannot copy and paste using localstorage more than once

### ISSUE THREAD

**Issue by reinoudk** [clientIO/JointJS_plus#70]
Pasting from localstorage currently doesn't work if the clipboard already has items. Copying and pasting between two screens therefore only works once at best. 

Could an option be added to force `joint.ui.Clipboard.pasteCells()` to use localstorage (and not check `this.isEmpty()`)?

**Comment by kumilingus** [comment]
Hi, what version do you use? I believe that's been already fixed in v1.7.2.

**Comment by reinoudk** [comment]
v1.7.1. I haven't yet done an update to 1.7.2 but I noticed it on the v2.0.0-alpha version as well.

**Comment by kumilingus** [comment]
Fixed in `v2.0.1`.
