### ISSUE TITLE
add object to page

### ISSUE THREAD

**Issue by avianmanagement** [clientIO/JointJS_plus#8]
Hi,
I just purchases JointJs+ this morning to do some work I want to do on an erd application.

In the kitchen sink demo I can drag object to the page no problem.

I have added a new button to the toolbar and want to click on it nad have it add a new object, say a rectangle, to the page.  I gan't figure out the command I need to use to add the new object.

Any help would be greatly appreciated as this is my 1st time with java script.

David Le Mesurier

**Comment by DavidDurman** [comment]
Hi David,

This can be done e.g. by registering a click event handler on your new toolbar button, creating a new JointJS element and adding it to the graph:

``` javascript
$('#btn-my-new-button-id').on('click', function() {

    var r = new joint.shapes.basic.Rect({
        position: { x: 500, y: 200 },
        size: { width: 100, height: 60 },
        attrs: {
            rect: { rx: 2, ry: 2, width: 50, height: 30, fill: '#27AE60' },
            text: { text: 'rect', fill: 'white', 'font-size': 10 }
        }
    });
    graph.addCell(r);
})
```

**Comment by avianmanagement** [comment]
Thank you very much that world very nicly.
